### ISSUE TITLE
environment and repo issues w/ eCLM

### ISSUE THREAD

**Issue by mvhulten** [HPSCTerrSys/TSMP2_workflow-engine#3] opened 2024-12-02 13:23 UTC
When I follow the workflow, `src/TSMP2` is pulled in.  From there one must `./build_tsmp2.sh --eclm` to build just eCLM.  This fails of course when I do not load modules, which I will do on the next try.

I think we should try standardise on Stages/2024 (almost DONE in TSMP2 repo; TODO here).

But trying to check consistency between repo, HEAD and environment, I see a detached HEAD and am unsure what is going on and what I should do:

```console
vanhulten1@jrlogin09:.../wfe-test/src/TSMP2$ git branch -v
* (HEAD detached at d61a0d4) d61a0d4 change submodule remote url of COSMO
  master                     15ff6eb build_tsmp2: correct check for alternative `parflow` (#41)
vanhulten1@jrlogin09:.../wfe-test/src/TSMP2$ git show -v
commit d61a0d49d418d9eb3040b293ad389435060d0ca8 (HEAD)
Author: Stefan Poll <s.poll@fz-juelich.de>
Date:   Fri Sep 13 10:44:36 2024 +0200

    change submodule remote url of COSMO

diff --git a/.gitmodules b/.gitmodules
index e6b1861..d31661e 100644
--- a/.gitmodules
+++ b/.gitmodules
@@ -28,5 +28,5 @@
        branch = tsmp-patches-v0.1
 [submodule "models/cosmo5.01_fresh"]
        path = models/cosmo5.01_fresh
-       url = https://icg4geo.icg.kfa-juelich.de/ModelSystems/tsmp_src/cosmo5.01_fresh.git
+       url = https://gitlab.jsc.fz-juelich.de/sdlts/tsmp_components_mirrors/cosmo5.01_fresh.git
        branch = tsmp-oasis
vanhulten1@jrlogin09:.../wfe-test/src/TSMP2$ git pull
You are not currently on a branch.
Please specify which branch you want to merge with.
See git-pull(1) for details.

    git pull <remote> <branch>

vanhulten1@jrlogin09:.../wfe-test/src/TSMP2$ git remote -v
origin  https://github.com/HPSCTerrSys/TSMP2.git (fetch)
origin  https://github.com/HPSCTerrSys/TSMP2.git (push)
vanhulten1@jrlogin09:.../wfe-test/src/TSMP2$ git pull origin master
From https://github.com/HPSCTerrSys/TSMP2
 * branch            master     -> FETCH_HEAD
hint: You have divergent branches and need to specify how to reconcile them.
hint: You can do so by running one of the following commands sometime before
hint: your next pull:
hint: 
hint:   git config pull.rebase false  # merge
hint:   git config pull.rebase true   # rebase
hint:   git config pull.ff only       # fast-forward only
hint: 
hint: You can replace "git config" with "git config --global" to set a default
hint: preference for all repositories. You can also pass --rebase, --no-rebase,
hint: or --ff-only on the command line to override the configured default per
hint: invocation.
fatal: Need to specify how to reconcile divergent branches.
```

**Comment by mvhulten** [comment] 2024-12-02 13:33
Commit d61a0d49d418d9eb3040b293ad389435060d0ca0 is [not](https://github.com/HPSCTerrSys/TSMP2/commit/d61a0d49d418d9eb3040b293ad389435060d0ca0) part of the TSMP2 repo.  Where does this commit come from?

**Comment by jjokella** [comment] 2024-12-02 13:35
Ok, I guess you just now did the same thing. Try this link: https://github.com/HPSCTerrSys/TSMP2/commit/d61a0d49d4  Somehow too much detail in the has made the link go bad.

**Comment by mvhulten** [comment] 2024-12-02 13:41
Right, thanks for the clarification @jjokella!

I messed up including a really non-existing hash (used to test!).  Fixed comment above.

In strict Git lingo, it is part of the repo but not of any branch (because of explanation you gave).

**Comment by jjokella** [comment] 2024-12-02 13:44
> In strict Git lingo, it is part of the repo but not of any branch (because of explanation you gave).
Fixed in my comment above. Thanks.

**Comment by mvhulten** [comment] 2024-12-02 13:53
@s-poll, in `.gitmodules` the TSMP2 module is at branch `dev_frontend`.  Why is this?

I'll presume it is not important and I it should be `master` that soon has the changes from `stages/2024`, but please confirm if this is ok.

**Comment by s-poll** [comment] 2024-12-02 14:22
Indeed the TSMP2 submodule should be updated after stages/2024 to the master. 

However, I am wondering why your eCLM build fails. There should be no need to load environments as they should be taken by default.

**Comment by s-poll** [comment] 2024-12-04 16:44
Actually, there should be only one file as a result otherwise the build is not clean. We could add a warning/abort message when this case occur.

Please be aware that you should remove the bin & bld directory when using TSMP2 build with a new environment as mentioned in [PR24](https://github.com/HPSCTerrSys/TSMP2/pull/24) of TSMP.

**Comment by mvhulten** [comment] 2024-12-10 10:51
First, a short correction about detached heads.

Detached heads are commits *that are not associated with any branch*.  In principle it is okay if a submodule are not on a branch, but it is… quirky and maybe sometimes more difficult to make sense of.

**Comment by mvhulten** [comment] 2024-12-10 11:07
I think I do see what you intend with displaying an abort message when there are multiple environment files.  I suppose this hangs on the idea that TSMP2 should provide no more than one environment file, because then it is univocal in what environment is to be used.

However, this is the WFE point of view, not per se that of TSMP2.  Practically, it can be great, at least for TSMP2, to provide several environment variables (but others may comment on that), and this is *fine*, because it is the task only for the WFE to make a simulation unambiguously reproducible.

I propose to accept that TSMP2 may provide multiple environment files and that the WFE picks one; that is really a task of the WFE.  WDYT?

**Comment by kvrigor** [comment] 2024-12-10 11:13
Unfortunately we can't do anything about DETACHED heads since `git submodule` work this way. It pins a specific version of a "sub-repo" by doing a `git checkout $COMMIT_HASH`. Note that running `git checkout $COMMIT_HASH` always ends up with a DETACHED head.

In the context of submodules, I interpret a DETACHED head as "tampering with this sub-repo is not encouraged". I believe this aligns with the reproducibility principle of the WFE. If you want to ensure that

```
# Make sure all models/* are updated
git submodule update --init --remote
git submodule update --force

**Comment by kvrigor** [comment] 2024-12-10 11:18
> I see a detached HEAD and am unsure what is going on and what I should do

Unfortunately we can't do anything about DETACHED heads since `git submodule` work this way. It pins a specific version of a "sub-repo" by doing a `git checkout $COMMIT_HASH`. Note that running `git checkout $COMMIT_HASH` always ends up with a DETACHED head.

In the context of submodules, I interpret a DETACHED head as "tampering with this sub-repo is not encouraged". I believe this aligns with the reproducibility principle of the WFE. If you want to ensure that build_tsmp2.sh builds the correct version of components, you can run these:

```bash
# Make sure all models/* are updated
git submodule update --init --remote
git submodule update --force

# Check if sub-repo versions are correct, which means
# no diffs under models/* 
git status
```

> I propose to accept that TSMP2 may provide multiple environment files and that the WFE picks one; that is really a task of the WFE. WDYT?

We're planning to do this on the `Stages/2025` PR, which would support multiple compiler toolchain and hence the possibility of multiple environment files.

**Comment by s-poll** [comment] 2024-12-10 14:47
IMO the provision of several environment files in TSMP2 is desired and was already discussed in [this TSMP2 PR](https://github.com/HPSCTerrSys/TSMP2/pull/27#discussion_r1867449263). However, the WFE should only take the one, which is used for building the model system. Thus, this number should always be always one. The find-command for the environment is done in the directory of the binaries.

For the git submodules I have nothing to add to Pauls statement, exspect that I would not call it "correct version of components"  but rather most up-to-date version.

**Closed** 2024-12-11 13:46 UTC
